defaults:
  - default_task
name: motion_control
train:
  cost:
    fall: 100
    goal_reached: -100
    error: 0.7
    integral_error: 0
    height: 20 # used only in sk8o_full
    integral_height: 0 # used only in sk8o_full
    wheel_input: 1.6e-3
    phi: 0.7
    roll: 0.01
    hip_input: 0.01
    step: 0
  end_conditions:
    phi: 1  # used only in sk8o_segway
    time: 20
    reference_error: 1e-2
    reference_derivative: 5e-1
  reference:
    height_range: [120e-3, 330e-3]
    forward_velocity_range: [-2, 2]
    angular_velocity_range: [-3, 3]
eval:
  cost:
    fall: 10000
    goal_reached: -10000
    error: 50
    height: 10 # used only in sk8o_full
    wheel_input: 1
    hip_input: 0.1
    step: 1
  end_conditions:
    phi: 1  # used only in sk8o_segway
    time: 20
    reference_error: 1e-2
    reference_derivative: 5e-1
  reference:
    height_range: [120e-3, 330e-3]
    forward_velocity_range: [-2, 2]
    angular_velocity_range: [0, 0]
observability: # what to include in the observation
  # - time
  - dot_x
  - dot_phi
  - dot_psi
  # - x
  - phi
  # - psi
  # - py
  # - px
  # - x_ref
  # - y_ref
  # - psi_ref
  - dot_x_ref
  - dot_psi_ref
  # - height_err_sum # used only in sk8o_full
  # - dot_x_err_sum
  # - dot_psi_err_sum
